services:
  db:
    image: postgres:16-alpine
    container_name: ecomerce-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecomerce
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Ecomerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
